// Domain Agent: executes one skill. In LIVE mode it calls Claude with the skill's
// SKILL.md body as its operating instructions; in MOCK mode it fills the skill's
// output template deterministically so the platform is demoable with no API key.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getSkill } from './skills.mjs';
import { createMessage, isLive, MODEL } from './anthropic.mjs';
import { recentArtifactContext } from './workspace.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
function agentPrompt(domain) {
  const f = path.join(__dirname, '..', 'agents', `${domain}.md`);
  return fs.existsSync(f) ? fs.readFileSync(f, 'utf8') : `You are the ${domain} domain agent.`;
}

export async function runDomainAgent({ projectId, domain, skillName, taskBrief, project }) {
  const skill = getSkill(domain, skillName);
  if (!skill) throw new Error(`Unknown skill ${domain}/${skillName}`);

  const context = recentArtifactContext(projectId);
  const stage = skill.stage || 'discovery';

  if (!isLive()) {
    return { content: mockArtifact(skill, taskBrief, project, context), stage, skill };
  }

  const system = [
    agentPrompt(domain),
    '',
    '## Active skill — follow these instructions precisely',
    skill.body,
    '',
    '## Output contract',
    `Produce a single, complete, well-structured Markdown artifact: ${skill.output}.`,
    'Do not include preamble or sign-off chatter — only the artifact itself.',
  ].join('\n');

  const user = [
    `Project: ${project?.name || projectId}`,
    project?.description ? `Project description: ${project.description}` : '',
    context ? `\nExisting workspace artifacts (for continuity):\n${context}` : '',
    `\nTask: ${taskBrief}`,
  ].filter(Boolean).join('\n');

  const resp = await createMessage({
    model: MODEL, max_tokens: 3072, system,
    messages: [{ role: 'user', content: user }],
  });
  const content = resp.content.filter(b => b.type === 'text').map(b => b.text).join('\n').trim();
  return { content, stage, skill };
}

function mockArtifact(skill, taskBrief, project, context) {
  return [
    `# ${titleCase(skill.name)} — ${project?.name || 'Project'}`,
    ``,
    `> Generated by the **${skill.domain}** domain agent using the **${skill.name}** skill.`,
    `> Mode: MOCK (no API key set). Add ANTHROPIC_API_KEY for live Claude generation.`,
    ``,
    `## Task brief`,
    taskBrief || '(none provided)',
    ``,
    `## What this skill produces`,
    skill.description,
    ``,
    `## Draft output (template)`,
    skill.body.split('\n').filter(l => l.startsWith('#') || l.startsWith('-') || l.startsWith('1.')).slice(0, 20).join('\n') || '- (skill body defines the structure)',
    ``,
    context ? `## Linked context\n${context}` : '',
  ].filter(Boolean).join('\n');
}
const titleCase = s => s.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
